services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: admin
      MYSQL_PASSWORD: test123!
      MYSQL_DATABASE: nestjs-auth
      TZ: 'utc'
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

